services:

  netdata:
    image: netdata/netdata
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  monocker:
    container_name: monocker
    image: petersem/monocker
    environment:
      - SERVER_LABEL='titania'
      - SERVER_AVATAR='https://content.invisioncic.com/u329766/monthly_2024_05/monocker.png.ba5ffdb390b627097d2a53645cf87350.png'
      - ONLY_OFFLINE_STATES='false'
      - EXCLUDE_EXITED='false'      
      - PERIOD=30
      - DISABLE_STARTUP_MSG='false'
      - SHA='false'
      - MESSAGE_PLATFORM
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    dns:
      - 10.80.0.2

  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    volumes:
      - speedtest:/config'
    environment:
      - TZ=
      - PGID=
      - PUID=
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    dns:
        - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:80 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
  speedtest: