networks:
  internal-proxy:
    external: true

volumes:
  speedtest:
  uptime-kuma:
  watchyourlan:

services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    volumes:
      - /var/run/docker.sock:/var/run/d-ocker.sock:ro
      - ./config/glances.conf:/etc/glances/glances.conf:ro
    environment:
      - VIRTUAL_HOST=mon.home.lan
      - VIRTUAL_PORT=61208
      - TZ=Europe/Madrid
      - GLANCES_OPT=-w
    network_mode: host
    pid: host
    restart: unless-stopped
    healthcheck:
      test: curl -sS --fail-with-body http://$$VIRTUAL_HOST || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  notifier:
    restart: unless-stopped
    container_name: docker-notifier
    image: lorcas/docker-telegram-notifier:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # for local instance
      # - ./certs:/certs # for remote instance
    environment:
      - TELEGRAM_NOTIFIER_BOT_TOKEN
      - TELEGRAM_NOTIFIER_CHAT_ID
      # ONLY_WHITELIST: true
      # DOCKER_HOST: tcp://example.com:2376 # http/https is detected by port number
      # DOCKER_CERT_PATH: /certs # should contain ca.pem, cert.pem, key.pem
    dns:
      - 10.80.0.2
    
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    networks:
      - internal-proxy
    volumes:
      - speedtest:/config
    environment:
      - VIRTUAL_HOST=speed.home.lan
      - VIRTUAL_PORT=80
      - TZ=Europe/Madrid
      - PGID=1000
      - PUID=1000
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    dns:
      - 10.80.0.2
    healthcheck:
      test: curl -sS --fail-with-body http://$$VIRTUAL_HOST || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    environment:
      - VIRTUAL_HOST=uptime.home.lan
      - VIRTUAL_PORT=3001
      - TZ=Europe/Madrid
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal-proxy
    restart: always
    dns:
      - 10.80.0.2
    healthcheck:
      test: curl -sS --fail-with-body http://$$VIRTUAL_HOST || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - VIRTUAL_HOST=logs.home.lan
      - VIRTUAL_PORT=8080
      - TZ=Europe/Madrid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal-proxy
    dns:
      - 10.80.0.2
    restart: unless-stopped
    # healthcheck:  # no shell
    #   test: curl -sS --fail-with-body http://$$VIRTUAL_HOST || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
  
  # https://github.com/aceberg/WatchYourLAN#quick-start
  watchyourlan:
    restart: unless-stopped
    image: aceberg/watchyourlan
    container_name: wyl
    network_mode: host
    volumes:
      - watchyourlan:/data
    environment:
      - VIRTUAL_HOST=wyl.home.lan
      - VIRTUAL_PORT=8840
      - TZ=Europe/Madrid
      - IFACES=enp0s25
      - THEME=darkly
      - HISTORY_DAYS=90
      - IGNOREIP=yes
      - SHOUTRRR_URL
    # healthcheck:  # curl not available
    #   test: curl -sS --fail-with-body http://$$VIRTUAL_HOST || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
