services:

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    volumes:
      - /var/run/docker.sock:/var/run/d-ocker.sock:ro
      - ./config/glances.conf:/etc/glances/glances.conf:ro
    environment:
      - TZ=Europe/Madrid
      - GLANCES_OPT=-w
    network_mode: host
    pid: host
    restart: unless-stopped
    healthcheck:
      test: curl -sS http://127.0.0.1:61208 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  notifier:
    restart: unless-stopped
    container_name: docker-notifier
    image: lorcas/docker-telegram-notifier:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # for local instance
      # - ./certs:/certs # for remote instance
    environment:
      - TELEGRAM_NOTIFIER_BOT_TOKEN
      - TELEGRAM_NOTIFIER_CHAT_ID
      # ONLY_WHITELIST: true
      # DOCKER_HOST: tcp://example.com:2376 # http/https is detected by port number
      # DOCKER_CERT_PATH: /certs # should contain ca.pem, cert.pem, key.pem
    dns:
      - 10.80.0.2
    
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    volumes:
      - speedtest:/config
    environment:
      - TZ=Europe/Madrid
      - PGID=1000
      - PUID=1000
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    dns:
      - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:80 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    environment:
      - TZ=Europe/Madrid
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 19301:3001
    restart: always
    dns:
      - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:3001 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9999:8080
    dns:
      - 10.80.0.2
    restart: unless-stopped
    # healthcheck:  # no shell
    #   test: curl -sS http://127.0.0.1:8080 || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
  
  # https://github.com/aceberg/WatchYourLAN#quick-start
  watchyourlan:
    restart: unless-stopped
    image: aceberg/watchyourlan
    container_name: wyl
    network_mode: host
    volumes:
      - watchyourlan:/data
    environment:
      - TZ=Europe/Madrid
      - IFACE=enp0s25
      - THEME=darkly
      - HISTORY_DAYS=90
      - IGNOREIP=yes
      - SHOUTRRR_URL
    # healthcheck:  # curl not available
    #   test: curl -sS http://127.0.0.1:8840 || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

volumes:
  speedtest:
  uptime-kuma:
  watchyourlan:

