services:

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    volumes:
      - /var/run/docker.sock:/var/run/d-ocker.sock:ro
      - ./config/glances.conf:/etc/glances/glances.conf:ro
    environment:
      - TZ=Europe/Madrid
    network_mode: host
    pid: host
    restart: unless-stopped

  monocker:
    container_name: monocker
    image: petersem/monocker
    environment:
      - SERVER_LABEL='titania'
      - SERVER_AVATAR='https://content.invisioncic.com/u329766/monthly_2024_05/monocker.png.ba5ffdb390b627097d2a53645cf87350.png'
      - ONLY_OFFLINE_STATES='false'
      - EXCLUDE_EXITED='false'      
      - PERIOD=30
      - DISABLE_STARTUP_MSG='false'
      - SHA='false'
      - MESSAGE_PLATFORM
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    dns:
      - 10.80.0.2

  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    volumes:
      - speedtest:/config
    environment:
      - TZ=Europe/Madrid
      - PGID=1000
      - PUID=1000
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    dns:
      - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:80 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    environment:
      - TZ=Europe/Madrid
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 19301:3001
    restart: always
    dns:
      - 10.80.0.2

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9999:8080
    dns:
      - 10.80.0.2
    restart: unless-stopped
    # healthcheck:
    #   test: curl -sS http://127.0.0.1:8080 || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    

volumes:
  speedtest:
  uptime-kuma: